name: build-push-image

on:
  push:
    branches: master

jobs:
  build-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/b1rdex/newrelic-telegram-relay:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
